[features]
seeds = false
skip-lint = false
[programs.localnet]
create_token_pda = "Fi1fHVT53eF5u6EZftV5yj6nsBmDvVJrcRM1GCGJCraW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
