[features]
seeds = false
skip-lint = false
[programs.localnet]
swap = "SGqsu3tC2MnFc3UuvxyNdQZa6EQF4PT7SNBSZuWfkrS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
